# Generated by Django 5.2.7 on 2025-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_pagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='composicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='descricao',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
