# Generated by Django 5.2.7 on 2025-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_itemestoque_codigo_itemestoque_composicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='composicao',
        ),
        migrations.RemoveField(
            model_name='itemestoque',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='composicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
